import { Roboto } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./components/layout/cart-context";

const roboto = Roboto({ subsets: ["latin"], weight: ['400','500','700'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <CartProvider><main className="max-w-4xl mx-auto p-4">{children}</main></CartProvider>
        </body>
    </html>
  );
}
